import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Database, Download, FileVideo, FolderOpen, FolderPlus, Frown, Meh, RefreshCw, Save, Smile, Tags, Trash2, Video, XCircle } from 'lucide-react';

type Directory = { path:string; lastScanned:number|null; videoCount:number };
type Extension = { extension:string; enabled:number };
type ScanJob = { id:string; directory:string; status:'running'|'completed'|'cancelled'|'failed'; scannedFiles:number; foundVideos:number; currentPath:string; error?:string };

export default function Admin() {
  const [directories,setDirectories]=useState<Directory[]>([]);
  const [busy,setBusy]=useState('');
  const [message,setMessage]=useState('');
  const [error,setError]=useState('');
  const [extensions,setExtensions]=useState<Extension[]>([]);
  const [ratingCounts,setRatingCounts]=useState<Record<string,number>>({});
  const [tagList,setTagList]=useState<{name:string;videoCount:number}[]>([]);
  const [scanJobs,setScanJobs]=useState<Record<string,ScanJob>>({});
  const [exclusions,setExclusions]=useState<string[]>([]);
  const [newExclusion,setNewExclusion]=useState('');
  const load=async()=>{const res=await fetch('/api/admin/directories');setDirectories(await res.json());};
  useEffect(()=>{load();fetch('/api/admin/extensions').then(r=>r.json()).then(setExtensions);fetch('/api/admin/ratings').then(r=>r.json()).then((rows:{rating:string;count:number}[])=>setRatingCounts(Object.fromEntries(rows.map(x=>[x.rating,Number(x.count)]))));fetch('/api/admin/tags').then(r=>r.json()).then(setTagList);fetch('/api/admin/exclusions').then(r=>r.json()).then(setExclusions);},[]);
  const pick=async()=>{setBusy('pick');setError('');const res=await fetch('/api/library/pick-directory',{method:'POST'});const data=await res.json();setBusy('');if(!res.ok){if(!data.canceled)setError(data.error);return;}await load();setMessage(data.alreadyExists?'此目錄已存在，未執行掃描。':'目錄已加入。請按該目錄的掃描按鈕開始建立片庫。');};
  const scan=async(path:string)=>{setError('');setMessage('');const res=await fetch('/api/admin/directories/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})});const job=await res.json();if(!res.ok){setError(job.error);return;}setScanJobs(items=>({...items,[path]:job}));const poll=async()=>{const statusRes=await fetch(`/api/admin/scans/${job.id}`);if(!statusRes.ok)return;const status:ScanJob=await statusRes.json();setScanJobs(items=>({...items,[path]:status}));if(status.status==='running')setTimeout(poll,700);else{await load();if(status.status==='completed')setMessage(`掃描完成：檢查 ${status.scannedFiles.toLocaleString()} 個檔案，找到 ${status.foundVideos} 部影片。`);else if(status.status==='failed')setError(status.error||'掃描失敗。');}};setTimeout(poll,400);};
  const cancelScan=async(path:string)=>{const job=scanJobs[path];if(!job)return;await fetch(`/api/admin/scans/${job.id}`,{method:'DELETE'});setScanJobs(items=>({...items,[path]:{...job,status:'cancelled'}}));setMessage('已取消掃描，原有片庫資料保持不變。');};
  const remove=async(path:string)=>{if(!confirm('確定從片庫移除此目錄？硬碟中的影片不會被刪除。'))return;setBusy(path);const res=await fetch('/api/library/directories',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})});const data=await res.json();setBusy('');if(!res.ok){setError(data.error);return;}await load();setMessage('目錄已從片庫移除，原始影片未被刪除。');};
  const date=(value:number|null)=>value?new Intl.DateTimeFormat('zh-TW',{dateStyle:'medium',timeStyle:'short'}).format(value):'尚未掃描';
  const toggleExtension=(extension:string)=>setExtensions(items=>items.map(item=>item.extension===extension?{...item,enabled:Number(!item.enabled)}:item));
  const saveExtensions=async()=>{setBusy('extensions');setError('');const res=await fetch('/api/admin/extensions',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({extensions:extensions.filter(x=>x.enabled).map(x=>x.extension)})});const data=await res.json();setBusy('');if(!res.ok){setError(data.error);return;}setExtensions(data);setMessage('副檔名設定已儲存。請個別掃描需要更新的目錄。');};
  const cleanupTags=async()=>{setBusy('tags');const res=await fetch('/api/admin/tags/cleanup',{method:'POST'});const data=await res.json();setBusy('');if(!res.ok){setError(data.error);return;}setTagList(data.tags);setMessage(`Tag 整理完成，已清除 ${data.removed} 個沒有影片的 Tag。`);};
  const resetAll=async()=>{const confirmation=prompt('這會清空所有 Hinami Player 資料與快取，但不會刪除原始影片。\n\n請輸入 RESET 確認：');if(confirmation!=='RESET')return;setBusy('reset');const res=await fetch('/api/admin/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation})});const data=await res.json();setBusy('');if(!res.ok){setError(data.error);return;}setDirectories([]);setTagList([]);setRatingCounts({});setMessage('Hinami Player 已完全重置，原始影片沒有被刪除。');};
  const addExcluded=async()=>{if(!newExclusion.trim())return;const res=await fetch('/api/admin/exclusions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pattern:newExclusion.trim()})});const data=await res.json();if(!res.ok){setError(data.error);return;}setExclusions(data);setNewExclusion('');};
  const removeExcluded=async(pattern:string)=>{const res=await fetch('/api/admin/exclusions',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({pattern})});setExclusions(await res.json());};
  return <main className="admin-page">
    <header className="admin-header"><a href="/"><ArrowLeft/>返回影片庫</a><div className="brand"><span>日</span>HINAMI <small>CONTROL</small></div><button className="watch" onClick={pick} disabled={busy==='pick'}><FolderPlus/>{busy==='pick'?'正在選擇…':'加入新目錄'}</button></header>
    <div className="admin-shell"><div className="admin-intro"><div><div className="eyebrow"><Database/> LIBRARY CONTROL</div><h1>目錄管理</h1><p>加入目錄時不會自動掃描；每個影片來源都由你決定何時建立或更新索引。</p></div><div className="admin-stat"><Video/><div><b>{directories.reduce((n,d)=>n+Number(d.videoCount),0)}</b><span>部影片</span></div></div><div className="admin-stat"><FolderOpen/><div><b>{directories.length}</b><span>個目錄</span></div></div></div>
      {message&&<div className="notice success"><CheckCircle2/>{message}<button onClick={()=>setMessage('')}>×</button></div>}{error&&<div className="notice failure"><XCircle/>{error}<button onClick={()=>setError('')}>×</button></div>}
      <section className="extension-panel"><div className="extension-title"><div><FileVideo/><div><h2>掃描副檔名</h2><p>選擇要辨識為影片的檔案類型。TS、MTS 容易與 TypeScript 程式碼混淆，預設停用。</p></div></div><button className="scan-button" onClick={saveExtensions} disabled={busy==='extensions'}><Save/>{busy==='extensions'?'儲存中':'儲存設定'}</button></div><div className="extension-grid">{extensions.map(item=><label className={item.enabled?'enabled':''} key={item.extension}><input type="checkbox" checked={Boolean(item.enabled)} onChange={()=>toggleExtension(item.extension)}/><span>.{item.extension}</span>{['ts','mts'].includes(item.extension)&&<small>容易混淆</small>}</label>)}</div><div className="extension-hint">設定不會立即變更現有影片；請在下方對指定目錄執行掃描。</div></section>
      <section className="rating-export"><div className="extension-title"><div><Download/><div><h2>匯出我的評分</h2><p>下載包含影片名稱與完整檔案路徑的 CSV 清單。</p></div></div></div><div className="rating-export-grid"><a href="/api/admin/ratings/export?rating=good"><Smile/><div><b>好</b><span>{ratingCounts.good||0} 部影片</span></div><Download/></a><a href="/api/admin/ratings/export?rating=medium"><Meh/><div><b>中等</b><span>{ratingCounts.medium||0} 部影片</span></div><Download/></a><a href="/api/admin/ratings/export?rating=bad"><Frown/><div><b>不好</b><span>{ratingCounts.bad||0} 部影片</span></div><Download/></a></div></section>
      <section className="tag-maintenance"><div className="extension-title"><div><Tags/><div><h2>整理 Tags</h2><p>目前共 {tagList.length} 個 Tag，其中 {tagList.filter(tag=>tag.videoCount===0).length} 個沒有影片。</p></div></div><button className="scan-button" onClick={cleanupTags} disabled={busy==='tags'}><RefreshCw className={busy==='tags'?'spin':''}/>{busy==='tags'?'整理中':'執行整理'}</button></div><div className="tag-summary">{tagList.slice(0,18).map(tag=><span className={tag.videoCount===0?'empty':''} key={tag.name}>{tag.name}<small>{tag.videoCount}</small></span>)}{tagList.length>18&&<span>還有 {tagList.length-18} 個…</span>}</div></section>
      <section className="exclusion-panel"><div className="extension-title"><div><FolderOpen/><div><h2>略過目錄</h2><p>掃描遇到下列名稱的資料夾時會直接跳過，可自行新增或移除。</p></div></div></div><div className="exclusion-add"><input value={newExclusion} onChange={e=>setNewExclusion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addExcluded()} placeholder="輸入目錄名稱，例如 build"/><button onClick={addExcluded}>加入略過清單</button></div><div className="exclusion-list">{exclusions.map(pattern=><span key={pattern}>{pattern}<button onClick={()=>removeExcluded(pattern)} title="移除規則">×</button></span>)}</div></section>
      <section className="directory-panel"><div className="panel-heading"><div><h2>影片來源</h2><p>掃描與移除只會影響所選取的目錄。</p></div></div>
        <div className="directory-table"><div className="directory-head"><span>目錄</span><span>影片數量</span><span>最後掃描／進度</span><span>操作</span></div>{directories.map(dir=>{const job=scanJobs[dir.path];const running=job?.status==='running';return <div className="directory-item" key={dir.path}><div className="dir-name"><FolderOpen/><div><b>{dir.path.split('/').filter(Boolean).at(-1)}</b><span title={dir.path}>{dir.path}</span></div></div><div><b>{running?job.foundVideos:Number(dir.videoCount).toLocaleString()}</b><small> 部</small></div><div className="scan-date">{running?<div className="scan-progress"><b>已檢查 {job.scannedFiles.toLocaleString()} 個檔案</b><span title={job.currentPath}>{job.currentPath}</span></div>:date(dir.lastScanned)}</div><div className="dir-actions">{running?<button className="cancel-button" onClick={()=>cancelScan(dir.path)}>取消</button>:<button className="scan-button" onClick={()=>scan(dir.path)}><RefreshCw/>掃描</button>}<button className="delete-button" disabled={running} onClick={()=>remove(dir.path)} title="移除目錄"><Trash2/></button></div></div>})}{!directories.length&&<div className="admin-empty"><FolderPlus/><h3>還沒有影片來源</h3><p>加入目錄後，按下該目錄的掃描按鈕建立片庫。</p><button className="watch" onClick={pick}>選擇資料夾</button></div>}</div>
      </section><section className="danger-zone"><div><Trash2/><div><h2>完全重置 Hinami Player</h2><p>清空目錄、影片索引、評分、播放記錄、Tags、設定及快取。原始影片不會被刪除。</p></div></div><button onClick={resetAll} disabled={busy==='reset'}>{busy==='reset'?'重置中…':'完全重置'}</button></section><p className="admin-footnote">移除來源或完全重置都不會修改、移動或刪除硬碟上的原始影片。</p></div>
  </main>;
}
