import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Database, Download, FileVideo, FolderOpen, FolderPlus, Frown, Meh, RefreshCw, Save, Smile, Tags, Trash2, Video, XCircle } from 'lucide-react';
import { LanguageSwitcher, useI18n } from './i18n';

type Directory = { path:string; lastScanned:number|null; videoCount:number };
type Extension = { extension:string; enabled:number };
type ScanJob = { id:string; directory:string; status:'running'|'completed'|'cancelled'|'failed'; scannedFiles:number; foundVideos:number; currentPath:string; error?:string };

export default function Admin() {
  const {language,t}=useI18n();
  const [directories,setDirectories]=useState<Directory[]>([]);
  const [busy,setBusy]=useState('');
  const [message,setMessage]=useState('');
  const [error,setError]=useState('');
  const [extensions,setExtensions]=useState<Extension[]>([]);
  const [ratingCounts,setRatingCounts]=useState<Record<string,number>>({});
  const [tagList,setTagList]=useState<{name:string;videoCount:number}[]>([]);
  const [scanJobs,setScanJobs]=useState<Record<string,ScanJob>>({});
  const [exclusions,setExclusions]=useState<string[]>([]);
  const [newExclusion,setNewExclusion]=useState('');
  const load=async()=>{const res=await fetch('/api/admin/directories');setDirectories(await res.json());};
  useEffect(()=>{load();fetch('/api/admin/extensions').then(r=>r.json()).then(setExtensions);fetch('/api/admin/ratings').then(r=>r.json()).then((rows:{rating:string;count:number}[])=>setRatingCounts(Object.fromEntries(rows.map(x=>[x.rating,Number(x.count)]))));fetch('/api/admin/tags').then(r=>r.json()).then(setTagList);fetch('/api/admin/exclusions').then(r=>r.json()).then(setExclusions);},[]);
  const pick=async()=>{setBusy('pick');setError('');const res=await fetch('/api/library/pick-directory',{method:'POST'});const data=await res.json();setBusy('');if(!res.ok){if(!data.canceled)setError(data.error);return;}await load();setMessage(data.alreadyExists?'此目錄已存在，未執行掃描。':'目錄已加入。請按該目錄的掃描按鈕開始建立片庫。');};
  const scan=async(path:string)=>{setError('');setMessage('');const res=await fetch('/api/admin/directories/scan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})});const job=await res.json();if(!res.ok){setError(job.error);return;}setScanJobs(items=>({...items,[path]:job}));const poll=async()=>{const statusRes=await fetch(`/api/admin/scans/${job.id}`);if(!statusRes.ok)return;const status:ScanJob=await statusRes.json();setScanJobs(items=>({...items,[path]:status}));if(status.status==='running')setTimeout(poll,700);else{await load();if(status.status==='completed')setMessage(`掃描完成：檢查 ${status.scannedFiles.toLocaleString()} 個檔案，找到 ${status.foundVideos} 部影片。`);else if(status.status==='failed')setError(status.error||'掃描失敗。');}};setTimeout(poll,400);};
  const cancelScan=async(path:string)=>{const job=scanJobs[path];if(!job)return;await fetch(`/api/admin/scans/${job.id}`,{method:'DELETE'});setScanJobs(items=>({...items,[path]:{...job,status:'cancelled'}}));setMessage('已取消掃描，原有片庫資料保持不變。');};
  const remove=async(path:string)=>{if(!confirm('確定從片庫移除此目錄？硬碟中的影片不會被刪除。'))return;setBusy(path);const res=await fetch('/api/library/directories',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})});const data=await res.json();setBusy('');if(!res.ok){setError(data.error);return;}await load();setMessage('目錄已從片庫移除，原始影片未被刪除。');};
  const date=(value:number|null)=>value?new Intl.DateTimeFormat(language,{dateStyle:'medium',timeStyle:'short'}).format(value):'—';
  const toggleExtension=(extension:string)=>setExtensions(items=>items.map(item=>item.extension===extension?{...item,enabled:Number(!item.enabled)}:item));
  const saveExtensions=async()=>{setBusy('extensions');setError('');const res=await fetch('/api/admin/extensions',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({extensions:extensions.filter(x=>x.enabled).map(x=>x.extension)})});const data=await res.json();setBusy('');if(!res.ok){setError(data.error);return;}setExtensions(data);setMessage('副檔名設定已儲存。請個別掃描需要更新的目錄。');};
  const cleanupTags=async()=>{setBusy('tags');const res=await fetch('/api/admin/tags/cleanup',{method:'POST'});const data=await res.json();setBusy('');if(!res.ok){setError(data.error);return;}setTagList(data.tags);setMessage(`Tag 整理完成，已清除 ${data.removed} 個沒有影片的 Tag。`);};
  const resetAll=async()=>{const confirmation=prompt('這會清空所有 Hinami Player 資料與快取，但不會刪除原始影片。\n\n請輸入 RESET 確認：');if(confirmation!=='RESET')return;setBusy('reset');const res=await fetch('/api/admin/reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirmation})});const data=await res.json();setBusy('');if(!res.ok){setError(data.error);return;}setDirectories([]);setTagList([]);setRatingCounts({});setMessage('Hinami Player 已完全重置，原始影片沒有被刪除。');};
  const addExcluded=async()=>{if(!newExclusion.trim())return;const res=await fetch('/api/admin/exclusions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pattern:newExclusion.trim()})});const data=await res.json();if(!res.ok){setError(data.error);return;}setExclusions(data);setNewExclusion('');};
  const removeExcluded=async(pattern:string)=>{const res=await fetch('/api/admin/exclusions',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({pattern})});setExclusions(await res.json());};
  return <main className="admin-page">
    <header className="admin-header"><a href="/"><ArrowLeft/>{t('back')}</a><div className="brand"><span>日</span>HINAMI <small>CONTROL</small></div><LanguageSwitcher/><button className="watch" onClick={pick} disabled={busy==='pick'}><FolderPlus/>{busy==='pick'?t('choosing'):t('addDirectory')}</button></header>
    <div className="admin-shell"><div className="admin-intro"><div><div className="eyebrow"><Database/> LIBRARY CONTROL</div><h1>{t('directoryControl')}</h1><p>{t('directoryIntro')}</p></div><div className="admin-stat"><Video/><div><b>{directories.reduce((n,d)=>n+Number(d.videoCount),0)}</b><span>{t('videos')}</span></div></div><div className="admin-stat"><FolderOpen/><div><b>{directories.length}</b><span>{t('directories')}</span></div></div></div>
      {message&&<div className="notice success"><CheckCircle2/>{message}<button onClick={()=>setMessage('')}>×</button></div>}{error&&<div className="notice failure"><XCircle/>{error}<button onClick={()=>setError('')}>×</button></div>}
      <section className="extension-panel"><div className="extension-title"><div><FileVideo/><div><h2>{t('extensions')}</h2><p>MP4 · WebM · MOV · MKV · WMV · AVI · VR</p></div></div><button className="scan-button" onClick={saveExtensions} disabled={busy==='extensions'}><Save/>{busy==='extensions'?t('saving'):t('save')}</button></div><div className="extension-grid">{extensions.map(item=><label className={item.enabled?'enabled':''} key={item.extension}><input type="checkbox" checked={Boolean(item.enabled)} onChange={()=>toggleExtension(item.extension)}/><span>.{item.extension}</span>{['ts','mts'].includes(item.extension)&&<small>TS</small>}</label>)}</div></section>
      <section className="rating-export"><div className="extension-title"><div><Download/><div><h2>{t('exportRatings')}</h2><p>CSV</p></div></div></div><div className="rating-export-grid"><a href="/api/admin/ratings/export?rating=good"><Smile/><div><b>{t('good')}</b><span>{ratingCounts.good||0} {t('videos')}</span></div><Download/></a><a href="/api/admin/ratings/export?rating=medium"><Meh/><div><b>{t('medium')}</b><span>{ratingCounts.medium||0} {t('videos')}</span></div><Download/></a><a href="/api/admin/ratings/export?rating=bad"><Frown/><div><b>{t('bad')}</b><span>{ratingCounts.bad||0} {t('videos')}</span></div><Download/></a></div></section>
      <section className="tag-maintenance"><div className="extension-title"><div><Tags/><div><h2>{t('tags')}</h2><p>{tagList.length} Tags</p></div></div><button className="scan-button" onClick={cleanupTags} disabled={busy==='tags'}><RefreshCw className={busy==='tags'?'spin':''}/>{t('tags')}</button></div><div className="tag-summary">{tagList.slice(0,18).map(tag=><span className={tag.videoCount===0?'empty':''} key={tag.name}>{tag.name}<small>{tag.videoCount}</small></span>)}</div></section>
      <section className="exclusion-panel"><div className="extension-title"><div><FolderOpen/><div><h2>{t('exclusions')}</h2><p>.git · node_modules · cache</p></div></div></div><div className="exclusion-add"><input value={newExclusion} onChange={e=>setNewExclusion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addExcluded()} placeholder="build"/><button onClick={addExcluded}>＋</button></div><div className="exclusion-list">{exclusions.map(pattern=><span key={pattern}>{pattern}<button onClick={()=>removeExcluded(pattern)}>×</button></span>)}</div></section>
      <section className="directory-panel"><div className="panel-heading"><div><h2>{t('sources')}</h2></div></div>
        <div className="directory-table"><div className="directory-head"><span>{t('directories')}</span><span>{t('videoCount')}</span><span>{t('lastScan')}</span><span>{t('actions')}</span></div>{directories.map(dir=>{const job=scanJobs[dir.path];const running=job?.status==='running';return <div className="directory-item" key={dir.path}><div className="dir-name"><FolderOpen/><div><b>{dir.path.split('/').filter(Boolean).at(-1)}</b><span title={dir.path}>{dir.path}</span></div></div><div><b>{running?job.foundVideos:Number(dir.videoCount).toLocaleString()}</b></div><div className="scan-date">{running?<div className="scan-progress"><b>{job.scannedFiles.toLocaleString()}</b><span title={job.currentPath}>{job.currentPath}</span></div>:date(dir.lastScanned)}</div><div className="dir-actions">{running?<button className="cancel-button" onClick={()=>cancelScan(dir.path)}>{t('cancel')}</button>:<button className="scan-button" onClick={()=>scan(dir.path)}><RefreshCw/>{t('scan')}</button>}<button className="delete-button" disabled={running} onClick={()=>remove(dir.path)}><Trash2/></button></div></div>})}{!directories.length&&<div className="admin-empty"><FolderPlus/><h3>{t('emptySources')}</h3><button className="watch" onClick={pick}>{t('selectFolder')}</button></div>}</div>
      </section><section className="danger-zone"><div><Trash2/><div><h2>{t('reset')}</h2></div></div><button onClick={resetAll} disabled={busy==='reset'}>{busy==='reset'?t('resetting'):t('fullReset')}</button></section></div>
  </main>;
}
