import { useEffect, useMemo, useState } from 'react';
import { Check, ChevronLeft, ChevronRight, Film, Folder, FolderCog, FolderPlus, Frown, History, LayoutGrid, Meh, Menu, Play, Search, Smile, Sparkles, Trash2, X } from 'lucide-react';
import Player from './Player';
import type { Library, Video } from './types';
import { LanguageSwitcher, useI18n } from './i18n';

const EMPTY:Library={directories:[],videos:[]};
const ALL='全部';
const PAGE_SIZE=10;
const bytes=(n:number)=>n>1e9?`${(n/1e9).toFixed(1)} GB`:`${(n/1e6).toFixed(0)} MB`;
type View='home'|'library'|'categories'|'directories'|'vr'|'history';

export default function App(){
  const {language,t}=useI18n();
  const copy={
    en:{pick:'Tainan Sunlight Selection',desc:'Continue exploring your private collection with direct local streaming and no cloud upload.',empty:'Your private cinema is ready',emptyDesc:'Add a video folder and Hinami Player will build your personal library.',first:'Add your first folder',clear:'Clear watch history',loadError:'Unable to load the library.',exists:'This folder is already in your library.',pickerError:'Unable to open the folder picker.',confirmHistory:'Clear all watch history?',categoryIntro:'Browse your library by category.',directoryIntro:'Browse videos by their source directory.'},
    'zh-TW':{pick:'府城日光精選',desc:'從你的私人收藏繼續探索。原始檔案直接串流，無需上傳至雲端。',empty:'你的私人影院，準備開演',emptyDesc:'加入電腦中的影片目錄，Hinami Player 會建立專屬片庫。',first:'加入第一個目錄',clear:'清空播放記錄',loadError:'無法讀取片庫。',exists:'此路徑已在片庫中。',pickerError:'無法開啟資料夾選擇器。',confirmHistory:'確定清空所有播放記錄？',categoryIntro:'依分類瀏覽片庫中的影片。',directoryIntro:'依影片來源目錄瀏覽完整架構。'},
    ja:{pick:'府城サンライト・セレクション',desc:'クラウドへアップロードせず、元ファイルを直接ストリーミングします。',empty:'あなただけの映画館を始めましょう',emptyDesc:'動画フォルダーを追加すると専用ライブラリを作成します。',first:'最初のフォルダーを追加',clear:'再生履歴を消去',loadError:'ライブラリを読み込めません。',exists:'このフォルダーは追加済みです。',pickerError:'フォルダー選択画面を開けません。',confirmHistory:'再生履歴をすべて消去しますか？',categoryIntro:'カテゴリー別に動画を表示します。',directoryIntro:'ソースフォルダー別に動画を表示します。'}
  }[language];
  const [library,setLibrary]=useState<Library>(EMPTY),[selected,setSelected]=useState<Video>();
  const [query,setQuery]=useState(''),[activeTag,setActiveTag]=useState(ALL),[activeDirectory,setActiveDirectory]=useState(ALL);
  const [activeRating,setActiveRating]=useState<'all'|'good'|'medium'|'bad'>('all');
  const [view,setView]=useState<View>('home'),[page,setPage]=useState(1);
  const [mobileMenuOpen,setMobileMenuOpen]=useState(false);
  const [history,setHistory]=useState<{videoId:string;watchedAt:number;progress:number;duration:number}[]>([]);
  const [dialog,setDialog]=useState(false),[path,setPath]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');try{const [a,b]=await Promise.all([fetch('/api/library'),fetch('/api/history')]);if(!a.ok)throw new Error();setLibrary(await a.json());setHistory(b.ok?await b.json():[]);}catch{setError(copy.loadError);}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  useEffect(()=>setPage(1),[view,query,activeTag,activeDirectory,activeRating]);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setMobileMenuOpen(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[]);
  const add=async()=>{if(!path.trim())return;const res=await fetch('/api/library/directories',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:path.trim()})});const data=await res.json();if(!res.ok){setError(data.error||copy.loadError);return;}setLibrary(data);setDialog(false);setPath('');if(data.alreadyExists)setError(copy.exists);};
  const pickDirectory=async()=>{setLoading(true);try{const res=await fetch('/api/library/pick-directory',{method:'POST'}),data=await res.json();if(!res.ok){if(!data.canceled)setError(data.error||copy.pickerError);return;}setLibrary(data);setDialog(false);if(data.alreadyExists)setError(copy.exists);}catch{setError(copy.pickerError);}finally{setLoading(false);}};
  const tags=useMemo(()=>[...new Set(library.videos.flatMap(v=>v.tags))].sort((a,b)=>a.localeCompare(b,'zh-Hant')),[library.videos]);
  const historyMap=useMemo(()=>new Map(history.map(x=>[x.videoId,x])),[history]);
  const filtered=useMemo(()=>library.videos.filter(v=>v.name.toLowerCase().includes(query.toLowerCase())&&(activeTag===ALL||v.tags.includes(activeTag))&&(activeDirectory===ALL||v.rootPath===activeDirectory)&&(activeRating==='all'||v.rating===activeRating)&&(view!=='vr'||v.vr)&&(view!=='history'||historyMap.has(v.id))),[library.videos,query,activeTag,activeDirectory,activeRating,view,historyMap]);
  const sorted=[...filtered].sort((a,b)=>view==='history'?(historyMap.get(b.id)?.watchedAt||0)-(historyMap.get(a.id)?.watchedAt||0):b.modifiedAt-a.modifiedAt);
  const totalPages=Math.max(1,Math.ceil(sorted.length/PAGE_SIZE)),items=view==='home'?sorted.slice(0,PAGE_SIZE):sorted.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE);
  const feature=sorted[0];
  const switchView=(next:View)=>{setView(next);setActiveTag(ALL);setActiveDirectory(ALL);setMobileMenuOpen(false);};
  const clearHistory=async()=>{if(!confirm(copy.confirmHistory))return;await fetch('/api/history',{method:'DELETE'});setHistory([]);};
  if(selected)return <Player video={selected} onClose={()=>{setSelected(undefined);void load();}}/>;
  const Row=({title,videos}:{title:string;videos:Video[]})=>videos.length?<section><div className="section-title"><h2>{title}</h2><ChevronRight/></div><div className="rail">{videos.map(v=><article className="card" key={v.id} onClick={()=>setSelected(v)}><div className="poster"><img src={`/api/thumbnail/${v.id}`} loading="lazy"/><div className="play"><Play fill="currentColor"/></div>{v.vr&&<b className="tag">360° VR</b>}<b className="format">DIRECT</b>{v.rating&&<b className={`rating-badge ${v.rating}`}>{v.rating==='good'?<Smile/>:v.rating==='medium'?<Meh/>:<Frown/>}{t(v.rating)}</b>}</div><h3>{v.name}</h3><p>{v.extension.toUpperCase()} · {bytes(v.size)}</p></article>)}</div></section>:null;
  const Pagination=()=>view!=='home'&&totalPages>1?<div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/>{t('previous')}</button><span>{t('page')} {page} / {totalPages}</span><button disabled={page===totalPages} onClick={()=>setPage(p=>p+1)}>{t('next')}<ChevronRight/></button></div>:null;
  const title=view==='categories'?t('categories'):view==='directories'?t('directoryTree'):view==='vr'?t('vr'):view==='history'?t('history'):t('library');
  return <main>
    <nav className={mobileMenuOpen?'menu-open':''}><div className="brand"><span>日</span>HINAMI <small>PLAYER</small></div><button className="menu-toggle" type="button" aria-label={mobileMenuOpen?'Close menu':'Open menu'} aria-expanded={mobileMenuOpen} aria-controls="main-navigation" onClick={()=>setMobileMenuOpen(open=>!open)}>{mobileMenuOpen?<X/>:<Menu/>}</button><div id="main-navigation" className="links">{([['home',t('home')],['library',t('library')],['categories',t('categories')],['directories',t('directoryTree')],['vr',t('vr')],['history',t('history')]] as [View,string][]).map(([key,label])=><button key={key} className={view===key?'selected':''} onClick={()=>switchView(key)}>{label}</button>)}</div><div className="nav-actions"><LanguageSwitcher/><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('search')}/></label><a className="icon-button" href="/admin" title={t('admin')}><FolderCog/></a><button className="add-button" onClick={()=>setDialog(true)}><FolderPlus/>{t('addDirectory')}</button></div></nav>{mobileMenuOpen&&<button className="menu-backdrop" aria-label="Close menu" onClick={()=>setMobileMenuOpen(false)}/>}
    {view==='home'?(feature?<header className="hero" style={{backgroundImage:`linear-gradient(90deg,#080a0c 5%,rgba(8,10,12,.74) 47%,rgba(8,10,12,.08)),linear-gradient(0deg,#080a0c,transparent 40%),url('/api/thumbnail/${feature.id}?wide=1')`}}><div className="hero-content"><div className="eyebrow"><Sparkles/>{copy.pick}</div><h1>{feature.name}</h1><p>{copy.desc}</p><button className="watch" onClick={()=>setSelected(feature)}><Play fill="currentColor"/>{t('play')}</button></div></header>:<header className="empty-hero"><div><Film/><h1>{copy.empty}</h1><p>{copy.emptyDesc}</p><button className="watch" onClick={()=>setDialog(true)}><FolderPlus/>{copy.first}</button></div></header>):<header className="collection-header"><div className="eyebrow">{view==='categories'?<LayoutGrid/>:view==='directories'?<Folder/>:view==='history'?<History/>:<Film/>} COLLECTION</div><h1>{title}</h1><p>{view==='categories'?copy.categoryIntro:view==='directories'?copy.directoryIntro:`${filtered.length} ${t('videos')}`}</p>{view==='history'&&history.length>0&&<button className="clear-history" onClick={clearHistory}><Trash2/>{copy.clear}</button>}</header>}
    <div className="content">{error&&<div className="error"><X/>{error}</div>}{view==='categories'&&activeTag===ALL?<div className="browser-grid">{tags.map(tag=><button key={tag} onClick={()=>setActiveTag(tag)}><LayoutGrid/><span>{tag}</span><small>{library.videos.filter(v=>v.tags.includes(tag)).length} {t('videos')}</small></button>)}</div>:view==='directories'&&activeDirectory===ALL?<div className="browser-grid">{library.directories.map(dir=><button key={dir} onClick={()=>setActiveDirectory(dir)}><Folder/><span>{dir.split(/[\\/]/).filter(Boolean).at(-1)||dir}</span><small>{library.videos.filter(v=>v.rootPath===dir).length} {t('videos')}</small><em>{dir}</em></button>)}</div>:<><div className="filter-toolbar"><div className="rating-filter"><button className={activeRating==='all'?'active':''} onClick={()=>setActiveRating('all')}>{t('allVideos')}</button>{(['good','medium','bad'] as const).map(r=><button key={r} className={activeRating===r?`active ${r}`:''} onClick={()=>setActiveRating(r)}>{r==='good'?<Smile/>:r==='medium'?<Meh/>:<Frown/>}{t(r)}</button>)}</div>{view==='categories'&&<button className="back-browser" onClick={()=>setActiveTag(ALL)}><ChevronLeft/>{t('categories')}</button>}{view==='directories'&&<button className="back-browser" onClick={()=>setActiveDirectory(ALL)}><ChevronLeft/>{t('directoryTree')}</button>}</div><Row title={activeTag!==ALL?activeTag:activeDirectory!==ALL?activeDirectory:view==='home'?t('recent'):title} videos={items}/>{filtered.length===0&&<div className="no-results"><Film/><h3>{t('noResults')}</h3><p>{t('noResultsHint')}</p></div>}<Pagination/></>}{library.directories.length>0&&<div className="library-note"><Check/>{library.directories.length} {t('directories')} · {library.videos.length} {t('videos')} · SQLite</div>}</div>
    {dialog&&<div className="modal-wrap" onMouseDown={()=>setDialog(false)}><div className="modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setDialog(false)}><X/></button><div className="modal-icon"><FolderPlus/></div><h2>{t('addVideoDirectory')}</h2><p>{t('pickerHelp')}</p><button className="watch full picker-button" onClick={pickDirectory} disabled={loading}><FolderPlus/>{loading?t('choosing'):t('chooseFolder')}</button><div className="or"><span>{t('orPath')}</span></div><input value={path} onChange={e=>setPath(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void add()} placeholder="D:\\Movies"/><small>{t('supported')}</small><button className="manual-add" onClick={add} disabled={!path.trim()}>{t('usePath')}</button></div></div>}
  </main>;
}
