import { useEffect, useMemo, useState } from 'react';
import { Check, ChevronRight, Film, FolderCog, FolderPlus, Frown, History, Meh, Play, RefreshCw, Search, Smile, Sparkles, Trash2, X } from 'lucide-react';
import Player from './Player';
import type { Library, Video } from './types';

const EMPTY: Library = { directories: [], videos: [] };
const bytes = (n: number) => n > 1e9 ? `${(n / 1e9).toFixed(1)} GB` : `${(n / 1e6).toFixed(0)} MB`;

export default function App() {
  const [library, setLibrary] = useState<Library>(EMPTY);
  const [selected, setSelected] = useState<Video>();
  const [query, setQuery] = useState('');
  const [activeTag, setActiveTag] = useState('全部');
  const [activeRating,setActiveRating]=useState<'all'|'good'|'medium'|'bad'>('all');
  const [view,setView]=useState<'home'|'library'|'vr'|'history'>('home');
  const [history,setHistory]=useState<{videoId:string;watchedAt:number;progress:number;duration:number}[]>([]);
  const [dialog, setDialog] = useState(false);
  const [manager, setManager] = useState(false);
  const [path, setPath] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async (scan = false) => { setLoading(true); setError(''); try { const [res,historyRes] = await Promise.all([fetch(scan ? '/api/library/scan' : '/api/library', { method: scan ? 'POST' : 'GET' }),fetch('/api/history')]); const data = await res.json(); if (!res.ok) throw new Error(data.error); setLibrary(data); setHistory(await historyRes.json()); } catch (e) { setError(e instanceof Error ? e.message : '無法讀取片庫'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const add = async () => { if (!path.trim()) return; const res = await fetch('/api/library/directories', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ path: path.trim() }) }); const data = await res.json(); if (!res.ok) { setError(data.error); return; } setLibrary(data); setDialog(false); setPath(''); if (data.alreadyExists) setError('此路徑已在片庫中；如需更新內容，請按右上角的重新掃描。'); };
  const pickDirectory = async () => { setLoading(true); setError(''); try { const res = await fetch('/api/library/pick-directory', { method: 'POST' }); const data = await res.json(); if (!res.ok) { if (!data.canceled) setError(data.error); return; } setLibrary(data); setDialog(false); setPath(''); if (data.alreadyExists) setError('此路徑已在片庫中；如需更新內容，請按右上角的重新掃描。'); } catch { setError('無法開啟資料夾選擇器。'); } finally { setLoading(false); } };
  const removeDirectory = async (directory:string) => { const res=await fetch('/api/library/directories',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:directory})}); const data=await res.json(); if(!res.ok){setError(data.error);return;} setLibrary(data); if(data.directories.length===0)setManager(false); };
  const tags = useMemo(() => [...new Set(library.videos.flatMap(v => v.tags))].sort((a,b) => a.localeCompare(b, 'zh-Hant')), [library.videos]);
  const historyMap=useMemo(()=>new Map(history.map(x=>[x.videoId,x])),[history]);
  const filtered = useMemo(() => library.videos.filter(v => v.name.toLowerCase().includes(query.toLowerCase()) && (activeTag === '全部' || v.tags.includes(activeTag)) && (activeRating==='all'||v.rating===activeRating) && (view!=='vr'||v.vr) && (view!=='history'||historyMap.has(v.id))), [library.videos, query, activeTag, activeRating, view, historyMap]);
  const recent = [...filtered].sort((a,b) => view==='history'?(historyMap.get(b.id)?.watchedAt||0)-(historyMap.get(a.id)?.watchedAt||0):b.modifiedAt-a.modifiedAt);
  const vr = filtered.filter(v => v.vr);
  const feature = recent[0];
  const clearHistory=async()=>{if(!confirm('確定清空所有播放記錄？影片與評分不會被刪除。'))return;await fetch('/api/history',{method:'DELETE'});setHistory([]);};
  if (selected) return <Player video={selected} onClose={() => {setSelected(undefined);load();}}/>;
  const Row = ({ title, items }: { title: string; items: Video[] }) => items.length ? <section><div className="section-title"><h2>{title}</h2><ChevronRight/></div><div className="rail">{items.map(v => <article className="card" key={v.id} onClick={() => setSelected(v)}><div className="poster"><img src={`/api/thumbnail/${v.id}`} loading="lazy"/><div className="play"><Play fill="currentColor"/></div>{v.vr && <b className="tag">360° VR</b>} {!v.native && <b className="format">轉碼</b>}{v.rating&&<b className={`rating-badge ${v.rating}`}>{v.rating==='good'?<Smile/>:v.rating==='medium'?<Meh/>:<Frown/>}{v.rating==='good'?'好':v.rating==='medium'?'中等':'不好'}</b>}</div><h3>{v.name}</h3><p>{v.extension.toUpperCase()} · {bytes(v.size)}</p></article>)}</div></section> : null;
  return <main>
    <nav><div className="brand"><span>日</span>HINAMI <small>PLAYER</small></div><div className="links"><button className={view==='home'?'selected':''} onClick={()=>setView('home')}>首頁</button><button className={view==='library'?'selected':''} onClick={()=>setView('library')}>我的片庫</button><button className={view==='vr'?'selected':''} onClick={()=>setView('vr')}>VR 空間</button><button className={view==='history'?'selected':''} onClick={()=>setView('history')}>播放記錄</button></div><div className="nav-actions"><label><Search/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜尋影片"/></label><a className="icon-button" href="/admin" title="目錄管理後台"><FolderCog/></a><button className="add-button" onClick={() => setDialog(true)}><FolderPlus/>加入目錄</button></div></nav>
    {view==='home'?(feature ? <header className="hero" style={{ backgroundImage: `linear-gradient(90deg, #080a0c 5%, rgba(8,10,12,.74) 47%, rgba(8,10,12,.08)), linear-gradient(0deg, #080a0c, transparent 40%), url('/api/thumbnail/${feature.id}?wide=1')` }}><div className="hero-content"><div className="eyebrow"><Sparkles/> 府城日光精選</div><h1>{feature.name}</h1><p>從你的私人收藏繼續探索。高畫質本機串流，無需上傳至雲端。</p><div><button className="watch" onClick={() => setSelected(feature)}><Play fill="currentColor"/>立即播放</button><span className="meta">{feature.extension.toUpperCase()} · {bytes(feature.size)}</span></div></div></header> : <header className="empty-hero"><div><Film/><h1>你的私人影院，準備開演</h1><p>加入電腦中的影片目錄，Hinami Player 會建立專屬片庫。</p><button className="watch" onClick={() => setDialog(true)}><FolderPlus/>加入第一個目錄</button></div></header>):<header className="collection-header"><div className="eyebrow">{view==='vr'?<><Sparkles/> IMMERSIVE COLLECTION</>:view==='history'?<><History/> WATCH HISTORY</>:<><Film/> PRIVATE LIBRARY</>}</div><h1>{view==='vr'?'VR 空間':view==='history'?'播放記錄':'我的片庫'}</h1><p>{view==='vr'?`共 ${library.videos.filter(v=>v.vr).length} 部沉浸式影片，可使用滑鼠拖曳探索視角。`:view==='history'?`共 ${history.length} 部最近觀看的影片，依播放時間排序。`:`完整瀏覽你的 ${library.videos.length} 部私人收藏。`}</p>{view==='history'&&history.length>0&&<button className="clear-history" onClick={clearHistory}><Trash2/>清空播放記錄</button>}</header>}
    <div className="content">{error && <div className="error"><X/>{error}</div>}<div className="filter-toolbar"><div className="rating-filter"><button className={activeRating==='all'?'active':''} onClick={()=>setActiveRating('all')}>全部影片</button><button className={activeRating==='good'?'active good':''} onClick={()=>setActiveRating('good')}><Smile/>好 <small>{library.videos.filter(v=>v.rating==='good').length}</small></button><button className={activeRating==='medium'?'active medium':''} onClick={()=>setActiveRating('medium')}><Meh/>中等 <small>{library.videos.filter(v=>v.rating==='medium').length}</small></button><button className={activeRating==='bad'?'active bad':''} onClick={()=>setActiveRating('bad')}><Frown/>不好 <small>{library.videos.filter(v=>v.rating==='bad').length}</small></button></div>{tags.length > 0 && <div className="tag-filter"><button className={activeTag === '全部' ? 'active' : ''} onClick={() => setActiveTag('全部')}>全部目錄</button>{tags.map(tag => <button key={tag} className={activeTag === tag ? 'active' : ''} onClick={() => setActiveTag(tag)}>{tag}</button>)}</div>}</div><Row title={query || activeTag !== '全部' || activeRating!=='all' ? `${activeRating==='good'?'好':activeRating==='medium'?'中等':activeRating==='bad'?'不好':activeTag==='全部'?'搜尋結果':activeTag} · ${filtered.length}` : '最近加入'} items={recent}/>{filtered.length===0&&(activeRating!=='all'||query)&&<div className="no-results"><Film/><h3>沒有符合條件的影片</h3><p>試著選擇其他評分或清除搜尋條件。</p></div>}<Row title="沉浸式 VR 收藏" items={vr}/>{library.directories.length > 0 && <div className="library-note"><Check/> 已連結 {library.directories.length} 個目錄 · 共 {library.videos.length} 部影片 · 資料儲存於 SQLite</div>}</div>
    {dialog && <div className="modal-wrap" onMouseDown={() => setDialog(false)}><div className="modal" onMouseDown={e => e.stopPropagation()}><button className="close" onClick={() => setDialog(false)}><X/></button><div className="modal-icon"><FolderPlus/></div><h2>加入影片目錄</h2><p>從 Finder 選擇資料夾。加入時不會掃描，請稍後到管理後台手動啟動。</p><button className="watch full picker-button" onClick={pickDirectory} disabled={loading}><FolderPlus/>{loading ? '正在加入…' : '選擇資料夾'}</button><div className="or"><span>或輸入完整路徑</span></div><input value={path} onChange={e => setPath(e.target.value)} onKeyDown={e => e.key === 'Enter' && add()} placeholder="例如：/Users/me/Movies"/><small>支援 MP4、WebM、MOV、MKV、WMV、AVI、M4V、OGV 與 VR 影片</small><button className="manual-add" onClick={add} disabled={!path.trim()}>使用此路徑加入</button></div></div>}
    {manager && <div className="modal-wrap" onMouseDown={() => setManager(false)}><div className="modal path-manager" onMouseDown={e => e.stopPropagation()}><button className="close" onClick={() => setManager(false)}><X/></button><div className="modal-icon"><FolderCog/></div><h2>管理片庫路徑</h2><p>新目錄只會在第一次加入時掃描。後續內容變動請使用右上角的重新掃描按鈕。</p><div className="path-list">{library.directories.length ? library.directories.map(directory=><div className="path-row" key={directory}><div><b>{directory.split('/').filter(Boolean).at(-1)}</b><span>{directory}</span></div><button title="從片庫移除" onClick={()=>removeDirectory(directory)}><Trash2/></button></div>) : <div className="no-path">尚未加入任何路徑</div>}</div><button className="watch full" onClick={()=>{setManager(false);setDialog(true)}}><FolderPlus/>加入其他目錄</button></div></div>}
  </main>;
}
