import { useEffect, useMemo, useState } from 'react';
import { Check, ChevronRight, Film, FolderCog, FolderPlus, Frown, History, Meh, Play, Search, Smile, Sparkles, Trash2, X } from 'lucide-react';
import Player from './Player';
import type { Library, Video } from './types';
import { LanguageSwitcher, useI18n } from './i18n';

const EMPTY: Library = { directories: [], videos: [] };
const bytes = (n: number) => n > 1e9 ? `${(n / 1e9).toFixed(1)} GB` : `${(n / 1e6).toFixed(0)} MB`;

export default function App() {
  const {language,t}=useI18n();
  const copy={
    en:{pick:'Tainan Sunlight Selection',desc:'Continue exploring your private collection with high-quality local streaming and no cloud upload.',empty:'Your private cinema is ready',emptyDesc:'Add a video folder and Hinami Player will build your personal library.',first:'Add your first folder',clear:'Clear watch history',results:'Search results',loadError:'Unable to load the library.',exists:'This folder is already in your library. Scan it again from Admin to update it.',pickerError:'Unable to open the folder picker.',confirmHistory:'Clear all watch history? Videos and ratings will not be deleted.'},
    'zh-TW':{pick:'府城日光精選',desc:'從你的私人收藏繼續探索。高畫質本機串流，無需上傳至雲端。',empty:'你的私人影院，準備開演',emptyDesc:'加入電腦中的影片目錄，Hinami Player 會建立專屬片庫。',first:'加入第一個目錄',clear:'清空播放記錄',results:'搜尋結果',loadError:'無法讀取片庫。',exists:'此路徑已在片庫中；請到管理後台重新掃描以更新內容。',pickerError:'無法開啟資料夾選擇器。',confirmHistory:'確定清空所有播放記錄？影片與評分不會被刪除。'},
    ja:{pick:'府城サンライト・セレクション',desc:'クラウドへアップロードせず、高画質のローカルストリーミングで自分のコレクションを楽しめます。',empty:'あなただけの映画館を始めましょう',emptyDesc:'動画フォルダーを追加すると、Hinami Player が専用ライブラリを作成します。',first:'最初のフォルダーを追加',clear:'再生履歴を消去',results:'検索結果',loadError:'ライブラリを読み込めません。',exists:'このフォルダーは追加済みです。更新するには管理画面から再スキャンしてください。',pickerError:'フォルダー選択画面を開けません。',confirmHistory:'再生履歴をすべて消去しますか？動画と評価は削除されません。'}
  }[language];
  const [library, setLibrary] = useState<Library>(EMPTY);
  const [selected, setSelected] = useState<Video>();
  const [query, setQuery] = useState('');
  const [activeTag, setActiveTag] = useState('全部');
  const [activeRating,setActiveRating]=useState<'all'|'good'|'medium'|'bad'>('all');
  const [view,setView]=useState<'home'|'library'|'vr'|'history'>('home');
  const [history,setHistory]=useState<{videoId:string;watchedAt:number;progress:number;duration:number}[]>([]);
  const [dialog, setDialog] = useState(false);
  const [path, setPath] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = async (scan = false) => { setLoading(true); setError(''); try { const [res,historyRes] = await Promise.all([fetch(scan ? '/api/library/scan' : '/api/library', { method: scan ? 'POST' : 'GET' }),fetch('/api/history')]); const data = await res.json(); if (!res.ok) throw new Error(language==='zh-TW'?data.error:copy.loadError); setLibrary(data); setHistory(await historyRes.json()); } catch { setError(copy.loadError); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const add = async () => { if (!path.trim()) return; const res = await fetch('/api/library/directories', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ path: path.trim() }) }); const data = await res.json(); if (!res.ok) { setError(language==='zh-TW'?data.error:copy.loadError); return; } setLibrary(data); setDialog(false); setPath(''); if (data.alreadyExists) setError(copy.exists); };
  const pickDirectory = async () => { setLoading(true); setError(''); try { const res = await fetch('/api/library/pick-directory', { method: 'POST' }); const data = await res.json(); if (!res.ok) { if (!data.canceled) setError(language==='zh-TW'?data.error:copy.pickerError); return; } setLibrary(data); setDialog(false); setPath(''); if (data.alreadyExists) setError(copy.exists); } catch { setError(copy.pickerError); } finally { setLoading(false); } };
  const tags = useMemo(() => [...new Set(library.videos.flatMap(v => v.tags))].sort((a,b) => a.localeCompare(b, 'zh-Hant')), [library.videos]);
  const historyMap=useMemo(()=>new Map(history.map(x=>[x.videoId,x])),[history]);
  const filtered = useMemo(() => library.videos.filter(v => v.name.toLowerCase().includes(query.toLowerCase()) && (activeTag === '全部' || v.tags.includes(activeTag)) && (activeRating==='all'||v.rating===activeRating) && (view!=='vr'||v.vr) && (view!=='history'||historyMap.has(v.id))), [library.videos, query, activeTag, activeRating, view, historyMap]);
  const recent = [...filtered].sort((a,b) => view==='history'?(historyMap.get(b.id)?.watchedAt||0)-(historyMap.get(a.id)?.watchedAt||0):b.modifiedAt-a.modifiedAt);
  const vr = filtered.filter(v => v.vr);
  const feature = recent[0];
  const clearHistory=async()=>{if(!confirm(copy.confirmHistory))return;await fetch('/api/history',{method:'DELETE'});setHistory([]);};
  if (selected) return <Player video={selected} onClose={() => {setSelected(undefined);load();}}/>;
  const Row = ({ title, items }: { title: string; items: Video[] }) => items.length ? <section><div className="section-title"><h2>{title}</h2><ChevronRight/></div><div className="rail">{items.map(v => <article className="card" key={v.id} onClick={() => setSelected(v)}><div className="poster"><img src={`/api/thumbnail/${v.id}`} loading="lazy"/><div className="play"><Play fill="currentColor"/></div>{v.vr && <b className="tag">360° VR</b>} {!v.native && <b className="format">HLS</b>}{v.rating&&<b className={`rating-badge ${v.rating}`}>{v.rating==='good'?<Smile/>:v.rating==='medium'?<Meh/>:<Frown/>}{t(v.rating)}</b>}</div><h3>{v.name}</h3><p>{v.extension.toUpperCase()} · {bytes(v.size)}</p></article>)}</div></section> : null;
  return <main>
    <nav><div className="brand"><span>日</span>HINAMI <small>PLAYER</small></div><div className="links"><button className={view==='home'?'selected':''} onClick={()=>setView('home')}>{t('home')}</button><button className={view==='library'?'selected':''} onClick={()=>setView('library')}>{t('library')}</button><button className={view==='vr'?'selected':''} onClick={()=>setView('vr')}>{t('vr')}</button><button className={view==='history'?'selected':''} onClick={()=>setView('history')}>{t('history')}</button></div><div className="nav-actions"><LanguageSwitcher/><label><Search/><input value={query} onChange={e => setQuery(e.target.value)} placeholder={t('search')}/></label><a className="icon-button" href="/admin" title={t('admin')}><FolderCog/></a><button className="add-button" onClick={() => setDialog(true)}><FolderPlus/>{t('addDirectory')}</button></div></nav>
    {view==='home'?(feature ? <header className="hero" style={{ backgroundImage: `linear-gradient(90deg, #080a0c 5%, rgba(8,10,12,.74) 47%, rgba(8,10,12,.08)), linear-gradient(0deg, #080a0c, transparent 40%), url('/api/thumbnail/${feature.id}?wide=1')` }}><div className="hero-content"><div className="eyebrow"><Sparkles/> {copy.pick}</div><h1>{feature.name}</h1><p>{copy.desc}</p><div><button className="watch" onClick={() => setSelected(feature)}><Play fill="currentColor"/>{t('play')}</button><span className="meta">{feature.extension.toUpperCase()} · {bytes(feature.size)}</span></div></div></header> : <header className="empty-hero"><div><Film/><h1>{copy.empty}</h1><p>{copy.emptyDesc}</p><button className="watch" onClick={() => setDialog(true)}><FolderPlus/>{copy.first}</button></div></header>):<header className="collection-header"><div className="eyebrow">{view==='vr'?<><Sparkles/> IMMERSIVE COLLECTION</>:view==='history'?<><History/> WATCH HISTORY</>:<><Film/> PRIVATE LIBRARY</>}</div><h1>{view==='vr'?t('vr'):view==='history'?t('history'):t('library')}</h1><p>{view==='vr'?`${library.videos.filter(v=>v.vr).length} VR ${t('videos')}`:view==='history'?`${history.length} ${t('videos')}`:`${library.videos.length} ${t('videos')}`}</p>{view==='history'&&history.length>0&&<button className="clear-history" onClick={clearHistory}><Trash2/>{copy.clear}</button>}</header>}
    <div className="content">{error && <div className="error"><X/>{error}</div>}<div className="filter-toolbar"><div className="rating-filter"><button className={activeRating==='all'?'active':''} onClick={()=>setActiveRating('all')}>{t('allVideos')}</button><button className={activeRating==='good'?'active good':''} onClick={()=>setActiveRating('good')}><Smile/>{t('good')} <small>{library.videos.filter(v=>v.rating==='good').length}</small></button><button className={activeRating==='medium'?'active medium':''} onClick={()=>setActiveRating('medium')}><Meh/>{t('medium')} <small>{library.videos.filter(v=>v.rating==='medium').length}</small></button><button className={activeRating==='bad'?'active bad':''} onClick={()=>setActiveRating('bad')}><Frown/>{t('bad')} <small>{library.videos.filter(v=>v.rating==='bad').length}</small></button></div>{tags.length > 0 && <div className="tag-filter"><button className={activeTag === '全部' ? 'active' : ''} onClick={() => setActiveTag('全部')}>{t('allFolders')}</button>{tags.map(tag => <button key={tag} className={activeTag === tag ? 'active' : ''} onClick={() => setActiveTag(tag)}>{tag}</button>)}</div>}</div><Row title={query || activeTag !== '全部' || activeRating!=='all' ? `${activeRating==='all'?(activeTag==='全部'?t('search'):activeTag):t(activeRating)} · ${filtered.length}` : t('recent')} items={recent}/>{filtered.length===0&&(activeRating!=='all'||query)&&<div className="no-results"><Film/><h3>{t('noResults')}</h3><p>{t('noResultsHint')}</p></div>}<Row title={t('vrCollection')} items={vr}/>{library.directories.length > 0 && <div className="library-note"><Check/> {library.directories.length} {t('directories')} · {library.videos.length} {t('videos')} · SQLite</div>}</div>
    {dialog && <div className="modal-wrap" onMouseDown={() => setDialog(false)}><div className="modal" onMouseDown={e => e.stopPropagation()}><button className="close" onClick={() => setDialog(false)}><X/></button><div className="modal-icon"><FolderPlus/></div><h2>{t('addVideoDirectory')}</h2><p>{t('pickerHelp')}</p><button className="watch full picker-button" onClick={pickDirectory} disabled={loading}><FolderPlus/>{loading ? t('choosing') : t('chooseFolder')}</button><div className="or"><span>{t('orPath')}</span></div><input value={path} onChange={e => setPath(e.target.value)} onKeyDown={e => e.key === 'Enter' && add()} placeholder="/Users/me/Movies · D:\\Movies"/><small>{t('supported')}</small><button className="manual-add" onClick={add} disabled={!path.trim()}>{t('usePath')}</button></div></div>}
  </main>;
}
